# Documentation http://goreleaser.com
before:
  hooks:
    - make assets/dist
builds:
- 
  main: main.go
  goos:
      - linux
  goarch:
    - amd64
    - 386
    - arm64    
  env:
    - CGO_ENABLED=0  
  hooks:
    pre: packr
    post: packr clean
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
